import pandas as pd
import plotly.express as px
import streamlit as st
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = BASE_DIR / "output"

ALL_EXCEPTIONS_FILE = OUTPUT_DIR / "all_exceptions.csv"
EXCEL_REPORT_FILE = OUTPUT_DIR / "Investment_Operations_Exception_Report.xlsx"


st.set_page_config(
    page_title="Daily Reconciliation Breaks Review",
    layout="wide",
)


@st.cache_data
def load_exception_data():
    """Load the combined exception report generated by the reconciliation engine."""
    return pd.read_csv(ALL_EXCEPTIONS_FILE)


def format_currency(value):
    """Format numeric values as currency."""
    return f"${value:,.2f}"


st.title("Daily Reconciliation Breaks Review")

st.caption(
    "Trade, position, and cash exceptions across internal books and custodian records."
)

st.caption("As of: 2026-06-09 | Data source: simulated internal, custodian, and portfolio records")

st.write(
    "This review is designed for an operations analyst to identify open reconciliation breaks, "
    "prioritize high-impact exceptions, and route issues to the appropriate operations team."
)

if not ALL_EXCEPTIONS_FILE.exists():
    st.error(
        "Exception report not found. Run `python src/reconciliation.py` first to generate output files."
    )
    st.stop()

exceptions = load_exception_data()

total_exceptions = len(exceptions)
high_risk_exceptions = len(exceptions[exceptions["risk_level"] == "High"])
critical_exceptions = len(exceptions[exceptions["priority"] == "Critical"])
total_dollar_impact = exceptions["estimated_dollar_impact"].sum()
average_days_open = exceptions["days_open"].mean()

st.subheader("Breaks Overview")

col1, col2, col3, col4, col5 = st.columns(5)

col1.metric("Total Exceptions", total_exceptions)
col2.metric("High Risk", high_risk_exceptions)
col3.metric("Critical Priority", critical_exceptions)
col4.metric("Est. Break Exposure", format_currency(total_dollar_impact))
col5.metric("Avg Days Open", round(average_days_open, 1))

st.divider()

st.subheader("Exception Analysis")

left_col, right_col = st.columns(2)

with left_col:
    source_breakdown = (
        exceptions.groupby("source")
        .size()
        .reset_index(name="exception_count")
        .sort_values("exception_count", ascending=False)
    )

    fig_source = px.bar(
        source_breakdown,
        x="source",
        y="exception_count",
        title="Open Breaks by Workflow",
        labels={
            "source": "Reconciliation Source",
            "exception_count": "Exception Count",
        },
    )

    st.plotly_chart(fig_source, use_container_width=True)

with right_col:
    risk_breakdown = (
        exceptions.groupby("risk_level")
        .size()
        .reset_index(name="exception_count")
        .sort_values("exception_count", ascending=False)
    )

    fig_risk = px.pie(
        risk_breakdown,
        names="risk_level",
        values="exception_count",
        title="Risk Mix",
    )

    st.plotly_chart(fig_risk, use_container_width=True)

left_col, right_col = st.columns(2)

with left_col:
    portfolio_impact = (
        exceptions.groupby("portfolio")
        .agg(
            exception_count=("record_id", "count"),
            estimated_dollar_impact=("estimated_dollar_impact", "sum"),
        )
        .reset_index()
        .sort_values("estimated_dollar_impact", ascending=False)
    )

    fig_portfolio = px.bar(
        portfolio_impact,
        x="portfolio",
        y="estimated_dollar_impact",
        title="Estimated Exposure by Portfolio",
        labels={
            "portfolio": "Portfolio",
            "estimated_dollar_impact": "Estimated Dollar Impact",
        },
    )

    st.plotly_chart(fig_portfolio, use_container_width=True)

with right_col:
    root_cause_breakdown = (
        exceptions.groupby("root_cause_category")
        .agg(
            exception_count=("record_id", "count"),
            estimated_dollar_impact=("estimated_dollar_impact", "sum"),
        )
        .reset_index()
        .sort_values("exception_count", ascending=False)
    )

    fig_root_cause = px.bar(
        root_cause_breakdown,
        x="root_cause_category",
        y="exception_count",
        title="Likely Root Cause",
        labels={
            "root_cause_category": "Root Cause Category",
            "exception_count": "Exception Count",
        },
    )

    st.plotly_chart(fig_root_cause, use_container_width=True)

st.divider()

st.subheader("Items Requiring First Review")

first_review = exceptions[
    (exceptions["priority"].isin(["Critical", "High"]))
].sort_values(
    ["estimated_dollar_impact", "days_open"],
    ascending=[False, False],
).head(5)

st.dataframe(
    first_review[
        [
            "record_id",
            "portfolio",
            "ticker",
            "break_type",
            "priority",
            "estimated_dollar_impact",
            "days_open",
            "exception_owner",
            "recommended_action",
        ]
    ],
    use_container_width=True,
)

st.subheader("Priority Queue")

priority_queue = exceptions.sort_values(
    ["priority", "estimated_dollar_impact", "days_open"],
    ascending=[True, False, False],
)

st.dataframe(
    priority_queue[
        [
            "source",
            "record_id",
            "portfolio",
            "ticker",
            "break_type",
            "risk_level",
            "priority",
            "exception_owner",
            "days_open",
            "estimated_dollar_impact",
            "root_cause_category",
            "recommended_action",
            "status",
        ]
    ],
    use_container_width=True,
)

st.divider()

st.subheader("Filter Exceptions")

filter_col1, filter_col2, filter_col3 = st.columns(3)

with filter_col1:
    selected_sources = st.multiselect(
        "Reconciliation Source",
        options=sorted(exceptions["source"].unique()),
        default=sorted(exceptions["source"].unique()),
    )

with filter_col2:
    selected_risk_levels = st.multiselect(
        "Risk Level",
        options=sorted(exceptions["risk_level"].unique()),
        default=sorted(exceptions["risk_level"].unique()),
    )

with filter_col3:
    selected_portfolios = st.multiselect(
        "Portfolio",
        options=sorted(exceptions["portfolio"].unique()),
        default=sorted(exceptions["portfolio"].unique()),
    )

filtered_exceptions = exceptions[
    (exceptions["source"].isin(selected_sources))
    & (exceptions["risk_level"].isin(selected_risk_levels))
    & (exceptions["portfolio"].isin(selected_portfolios))
]

st.dataframe(filtered_exceptions, use_container_width=True)

st.divider()

st.subheader("Download Reports")

csv_data = filtered_exceptions.to_csv(index=False)

st.download_button(
    label="Download Filtered Exceptions CSV",
    data=csv_data,
    file_name="filtered_exceptions.csv",
    mime="text/csv",
)

if EXCEL_REPORT_FILE.exists():
    with open(EXCEL_REPORT_FILE, "rb") as file:
        st.download_button(
            label="Download Full Excel Exception Report",
            data=file,
            file_name="Investment_Operations_Exception_Report.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )

with st.expander("Methodology Notes"):
    st.write(
        "Risk level, priority, owner, and root cause are assigned using rule-based logic for this simulated workflow. "
        "Dollar impact is estimated using trade quantity and price, position quantity and market price, or cash balance differences. "
        "In a production operations environment, these rules would be validated against internal controls, settlement procedures, and escalation policies."
    )